spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortenerdb?createDatabaseIfNotExist=true
    username: root
    password: Shivam@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ac12dec5f4905eba8f9d3b7e45c8a9d6e1f2a3c4b5d6e7f8a9b0c1d2e3f4a5b6c
  expiration: 172800000

frontend:
  url: http://localhost:5173
